name: dart_doc_syncer
version: 0.0.0
description: >
  Updates a documentation repository for an angular.io Dart example based on
  latest content of the raw content under public/docs/_examples in the main
  angular.io repository.
author: Thibault Sottiaux <thso@google.com>
dependencies:
  logging: ^0.11.2
  path: '^1.2.0'
dev_dependencies:
  test: ^0.12.8
